export const items = [
	{
	id: 1,
	title: 'Leather chair',
	img: 'leatherchair.jpg',
	desc: 'A piece of furniture designed for the purpose of allowing a single person to sit or recline',
	category: 'Chairs',
	price: '59.99',
	},
	{
	id: 2,
	title: 'Sofa',
	img: 'sofa.jpg',
	desc: 'A long, comfortable seat with a back and usually with arms',
	category: 'Sofas',
	price: '325.99',
	},
	{
	id: 3,
	title: 'Table',
	img: 'table.jpg',
	desc: 'A table, especially one seating several persons,especially the major or more formal meals.',
	category: 'Tables',
	price: '211.59',
	},
	{
	id: 4,
	title: 'Ottoman',
	img: 'ottoman.jpg',
	desc: 'Textile fabric in rib weave with strong transverse ribs caused by multiple weft threads made of wool or other fibers',
	category: 'Sofas',
	price: '198.32',
	},
	{
	id: 5,
	title: 'Floor lamp',
	img: 'floorlamp.jpg',
	desc: 'a small appliance that holds an electric bulb and produces light.',
	category: 'Lamps',
	price: '126.74',
	},
	{
	id: 6,
	title: 'Coffee table',
	img: 'coffeetable.jpg',
	desc: 'A piece of furniture designed for the purpose of allowing a single person to sit or recline',
	category: 'Tables',
	price: '203.58',
	},
	{
	id: 7,
	title: 'Armchair',
	img: 'armchair.jpg',
	desc: 'A piece of furniture designed for the purpose of allowing a single person to sit or recline',
	category: 'Chairs',
	price: '311.36',
	},
	{
	id: 8,
	title: 'Leather sofa',
	img: 'leathersofa.jpg',
	desc: 'A long, comfortable seat with a back and usually with arms',
	category: 'Sofas',
	price: '509.87',
	},
	{
	id: 9,
	title: 'Dinner table',
	img: 'dinnertable.jpg',
	desc: 'A table, especially one seating several persons, where meals are served and eaten, especially the major or more formal meals.',
	category: 'Tables',
	price: '426.15',
	},
	{
	id: 10,
	title: 'Cabinets for the kitchen',
	img: 'kitchen.jpg',
	desc: 'The main functions of a kitchen are to store, prepare and cook food (and to complete related tasks such as dishwashing',
	category: 'Kitchens',
	price: '1687.30',
	},
	{
	id: 11,
	title: 'Office table',
	img: 'officechair.jpg',
	desc: 'Place a memo book or notepad on your desk where you can write notes and lists of things to do.',
	category: 'Tables',
	price: '346.25',
	},
	{
	id: 12,
	title: 'Desk lamp',
	img: 'desklamp.jpg',
	desc: 'A small appliance that holds an electric bulb and produces light.',
	category: 'Lamps',
	price: '59.99',
	},
	{
	id: 13,
	title: 'Plastic chair',
	img: 'plasticchair.jpg',
	desc: 'A piece of furniture designed for the purpose of allowing a single person to sit or recline',
	category: 'Chairs',
	price: '98.98',
	},
	{
	id: 14,
	title: 'Wooden chair',
	img: 'woodenchair.jpg',
	desc: 'For the purpose of allowing a single person to sit or recline',
	category: 'Chairs',
	price: '87.99',
	},
	{
	id: 15,
	title: 'Seat chair',
	img: 'chair.jpg',
	desc: 'Designed for the purpose of allowing a single person to sit or recline',
	category: 'Chairs',
	price: '87.99',
	},
	{
	id: 16,
	title: 'Cabinets for the kitchen',
	img: 'kitchenone.jpg',
	desc: 'The main functions of a kitchen are to store, prepare and cook food (and to complete related tasks such as dishwashing',
	category: 'Kitchens',
	price: '1635.70',
	},
	{
	id: 17,
	title: 'Cabinets for the kitchen',
	img: 'kitchentwo.jpg',
	desc: 'The main functions of a kitchen are to store, prepare and cook food (and to complete related tasks such as dishwashing',
	category: 'Kitchens',
	price: '1528.50',
	},
	{
	id: 18,
	title: 'Desk lamp',
	img: 'lampone.jpg',
	desc: 'A small appliance that holds an electric bulb and produces light.',
	category: 'Lamps',
	price: '89.99',
	},
]

export const categories = [
    "All",
    "Chairs",
    "Sofas",
    "Tables",
    "Lamps",
    "Kitchens"
]
